const BASE = 'future-factory';
const PLANNING_COLLECTION = `${BASE}/production/digital_planning`;
const TRACKING_COLLECTION = `${BASE}/production/tracked_products`;
const PLANNING_EVENTS_COLLECTION = `${BASE}/production/events`;
const PLANNING_EVENTS_ARCHIVE_COLLECTION = `${BASE}/production/events_archive`;
const EFFICIENCY_COLLECTION = `${BASE}/production/efficiency_hours`;
const IMPORT_RUNS_COLLECTION = `${BASE}/integrations/import_runs`;
const AI_RATE_LIMIT_COLLECTION = `${BASE}/security/ai_rate_limits`;
const CLIENT_ERROR_LOG_COLLECTION = `${BASE}/logs/client_errors`;
const ATPS_PRESENCE_STATE_COLLECTION = `${BASE}/integrations/atps_presence`;
const ATPS_PRESENCE_SESSION_COLLECTION = `${BASE}/integrations/atps_presence_sessions`;
const ATPS_PRESENCE_MACHINE_ID = 'ATPS_AANWEZIGHEID';
const STATS_TODAY_DOC = `${BASE}/stats/today`;
const STATS_DAILY_COLLECTION = `${BASE}/stats/daily`;
const STORAGE_IMPORT_FOLDER = 'imports/planning/';
const ALLOWED_IMPORT_EXTENSIONS = ['.xlsx', '.xlsm', '.xls'];
const AI_RATE_LIMIT_WINDOW_MS = 60 * 1000;
const AI_RATE_LIMIT_MAX_REQUESTS = 20;
const AI_ALLOWED_MODELS = new Set([
  'gemini-2.5-flash',
  'gemini-2.0-flash',
]);
const AI_MAX_MESSAGES = 80;
const AI_MAX_MESSAGE_CHARS = 5000;
const AI_MAX_SYSTEM_PROMPT_CHARS = 12000;
const AI_MAX_TOTAL_CHARS = 50000;
const AI_MAX_CLIENT_ERROR_MSG = 1600;
const AI_MAX_CLIENT_ERROR_STACK = 4000;
const DEFAULT_SCOPED_DEPARTMENT = 'Fittings';
const DEFAULT_SCOPED_MACHINE = 'UNASSIGNED';

module.exports = {
  BASE,
  PLANNING_COLLECTION,
  TRACKING_COLLECTION,
  PLANNING_EVENTS_COLLECTION,
  PLANNING_EVENTS_ARCHIVE_COLLECTION,
  EFFICIENCY_COLLECTION,
  IMPORT_RUNS_COLLECTION,
  AI_RATE_LIMIT_COLLECTION,
  CLIENT_ERROR_LOG_COLLECTION,
  ATPS_PRESENCE_STATE_COLLECTION,
  ATPS_PRESENCE_SESSION_COLLECTION,
  ATPS_PRESENCE_MACHINE_ID,
  STATS_TODAY_DOC,
  STATS_DAILY_COLLECTION,
  STORAGE_IMPORT_FOLDER,
  ALLOWED_IMPORT_EXTENSIONS,
  AI_RATE_LIMIT_WINDOW_MS,
  AI_RATE_LIMIT_MAX_REQUESTS,
  AI_ALLOWED_MODELS,
  AI_MAX_MESSAGES,
  AI_MAX_MESSAGE_CHARS,
  AI_MAX_SYSTEM_PROMPT_CHARS,
  AI_MAX_TOTAL_CHARS,
  AI_MAX_CLIENT_ERROR_MSG,
  AI_MAX_CLIENT_ERROR_STACK,
  DEFAULT_SCOPED_DEPARTMENT,
  DEFAULT_SCOPED_MACHINE,
};
