import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { ChevronRight, ImageIcon, } from "lucide-react";
/**
 * ProductCard: Toont een product in de catalogus.
 * GEFIXT: Afbeelding is nu zichtbaar in het overzicht.
 */
const ProductCard = React.memo(({ product, onClick }) => {
    return (_jsxs("div", { onClick: () => onClick(product), className: "bg-white rounded-[32px] border border-slate-200 shadow-sm hover:shadow-xl hover:border-blue-300 transition-all cursor-pointer group flex flex-col overflow-hidden animate-in fade-in zoom-in duration-300", children: [_jsxs("div", { className: "relative aspect-video w-full bg-slate-100 overflow-hidden", children: [product.imageUrl ? (_jsx("img", { src: product.imageUrl, alt: product.name, className: "w-full h-full object-contain p-2 group-hover:scale-105 transition-transform duration-500" })) : (_jsxs("div", { className: "w-full h-full flex flex-col items-center justify-center text-slate-300 gap-2", children: [_jsx(ImageIcon, { size: 40, strokeWidth: 1.5 }), _jsx("span", { className: "text-[8px] font-black uppercase tracking-widest", children: "Geen Afbeelding" })] })), _jsx("div", { className: "absolute top-3 left-3", children: _jsx("span", { className: "bg-slate-900/80 backdrop-blur-md text-white text-[8px] font-black px-2 py-1 rounded-lg uppercase tracking-widest border border-white/20", children: product.label || "Standaard" }) })] }), _jsxs("div", { className: "p-6 flex-1 flex flex-col text-left", children: [_jsxs("div", { className: "mb-4", children: [_jsx("h3", { className: "text-sm font-black text-slate-900 uppercase italic tracking-tight line-clamp-2 leading-tight", children: product.name }), _jsx("p", { className: "text-[9px] font-bold text-slate-400 font-mono mt-1 uppercase tracking-tighter", children: product.articleCode || product.id })] }), _jsxs("div", { className: "mt-auto grid grid-cols-2 gap-2", children: [_jsxs("div", { className: "bg-slate-50 p-2 rounded-xl border border-slate-100 flex flex-col", children: [_jsx("span", { className: "text-[7px] font-black text-blue-500 uppercase tracking-widest", children: "Druk" }), _jsxs("span", { className: "text-xs font-black text-slate-700 leading-none", children: ["PN ", product.pressure || product.pn] })] }), _jsxs("div", { className: "bg-slate-50 p-2 rounded-xl border border-slate-100 flex flex-col", children: [_jsx("span", { className: "text-[7px] font-black text-emerald-500 uppercase tracking-widest", children: "Maat" }), _jsxs("span", { className: "text-xs font-black text-slate-700 leading-none", children: ["ID ", product.diameter || product.dn] })] })] }), _jsxs("div", { className: "mt-4 pt-4 border-t border-slate-50 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: `w-1.5 h-1.5 rounded-full ${product.status === "approved"
                                            ? "bg-emerald-500 animate-pulse"
                                            : "bg-orange-400"}` }), _jsx("span", { className: "text-[8px] font-black uppercase text-slate-400 tracking-widest", children: product.status === "approved" ? "Live" : "Concept" })] }), _jsx(ChevronRight, { size: 14, className: "text-slate-300 group-hover:text-blue-500 group-hover:translate-x-1 transition-all" })] })] })] }));
});
export default ProductCard;
