import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Package, FileText, Target, Layers, Database, ChevronRight, ShieldCheck, Hash, } from "lucide-react";
/**
 * SpecsView V3.0 - Blueprints Overview
 * Toont een visueel overzicht van alle technische templates die zijn opgeslagen in de root.
 * Helpt Engineers om snel te valideren welke variabelen (zoals TW, L, B1) actief zijn per type.
 */
const SpecsView = ({ blueprints = {} }) => {
    // Sorteer de blueprints: Boringen eerst, daarna de rest
    const sortedEntries = Object.entries(blueprints).sort(([keyA], [keyB]) => {
        if (keyA.startsWith("BORE_") && !keyB.startsWith("BORE_"))
            return -1;
        if (!keyA.startsWith("BORE_") && keyB.startsWith("BORE_"))
            return 1;
        return keyA.localeCompare(keyB);
    });
    return (_jsxs("div", { className: "space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 text-left", children: [_jsxs("div", { className: "bg-white p-8 rounded-[40px] shadow-sm border border-slate-200 flex flex-col md:flex-row items-center justify-between gap-6 overflow-hidden relative", children: [_jsx("div", { className: "absolute top-0 right-0 p-8 opacity-5 rotate-12", children: _jsx(FileText, { size: 120 }) }), _jsxs("div", { className: "flex items-center gap-6 relative z-10", children: [_jsx("div", { className: "p-4 bg-orange-500 text-white rounded-3xl shadow-lg shadow-orange-200", children: _jsx(Package, { size: 32 }) }), _jsxs("div", { children: [_jsxs("h3", { className: "text-2xl font-black text-slate-900 uppercase italic tracking-tighter leading-none", children: ["Technical ", _jsx("span", { className: "text-orange-500", children: "Inventory" })] }), _jsxs("p", { className: "text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-2 flex items-center gap-2", children: [_jsx(ShieldCheck, { size: 12, className: "text-emerald-500" }), " Overzicht van alle geactiveerde Blueprints"] })] })] }), _jsxs("div", { className: "bg-slate-50 px-6 py-3 rounded-2xl border border-slate-100 text-right shrink-0", children: [_jsx("span", { className: "text-[9px] font-black text-slate-400 uppercase block mb-1", children: "Totaal Templates" }), _jsxs("span", { className: "text-xl font-black text-slate-800 italic", children: [sortedEntries.length, " Records"] })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: sortedEntries.length > 0 ? (sortedEntries.map(([key, bp]) => {
                    const isBore = key.startsWith("BORE_");
                    return (_jsxs("div", { className: "bg-white rounded-[35px] border-2 border-slate-100 shadow-sm hover:shadow-xl hover:border-blue-400 transition-all group overflow-hidden flex flex-col", children: [_jsx("div", { className: `p-6 flex justify-between items-start border-b ${isBore
                                    ? "bg-blue-50/50 border-blue-100"
                                    : "bg-slate-50/50 border-slate-100"}`, children: _jsxs("div", { className: "text-left", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [isBore ? (_jsx(Target, { size: 14, className: "text-blue-600" })) : (_jsx(Layers, { size: 14, className: "text-purple-600" })), _jsx("span", { className: "text-[9px] font-black text-slate-400 uppercase tracking-[0.2em] italic", children: isBore ? "Boring Template" : "Fitting Template" })] }), _jsx("h4", { className: "font-black text-slate-900 text-lg tracking-tighter uppercase italic leading-none", children: key.replace("BORE_", "") })] }) }), _jsxs("div", { className: "p-6 flex-1 space-y-4", children: [_jsxs("div", { className: "bg-slate-50 rounded-2xl p-3 border border-slate-100", children: [_jsx("p", { className: "text-[8px] font-black text-slate-400 uppercase mb-2 ml-1", children: "Database Key" }), _jsx("code", { className: "text-[10px] font-mono font-bold text-blue-600 break-all", children: key })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("p", { className: "text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1 flex items-center gap-2", children: [_jsx(Hash, { size: 10 }), " Actieve Variabelen (", bp.fields?.length || 0, ")"] }), _jsx("div", { className: "flex flex-wrap gap-1.5", children: bp.fields && bp.fields.length > 0 ? (bp.fields.map((f) => (_jsx("span", { className: "px-2.5 py-1.5 bg-white text-slate-700 text-[10px] font-black rounded-lg border border-slate-200 shadow-sm group-hover:border-blue-200 transition-colors uppercase italic", children: f }, f)))) : (_jsx("span", { className: "text-[10px] text-slate-300 italic py-2 uppercase", children: "Geen velden gekoppeld" })) })] })] }), _jsxs("div", { className: "px-6 py-4 bg-slate-50/30 border-t border-slate-50 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-1.5 opacity-40", children: [_jsx(Database, { size: 10 }), _jsx("span", { className: "text-[8px] font-black uppercase tracking-tighter", children: "Sync Mode: Root" })] }), _jsx(ChevronRight, { size: 14, className: "text-slate-200 group-hover:text-blue-500 group-hover:translate-x-1 transition-all" })] })] }, key));
                })) : (_jsxs("div", { className: "col-span-full py-24 text-center bg-white rounded-[50px] border-2 border-dashed border-slate-200 opacity-50 flex flex-col items-center", children: [_jsx(Database, { size: 64, className: "text-slate-300 mb-4" }), _jsx("p", { className: "font-black uppercase tracking-[0.3em] text-xs text-slate-400", children: "Geen technische specificaties gevonden in de root" })] })) }), _jsxs("div", { className: "p-8 bg-slate-900 rounded-[40px] border border-white/5 shadow-2xl relative overflow-hidden text-white flex items-start gap-6", children: [_jsx("div", { className: "absolute top-0 right-0 p-8 opacity-5 rotate-12", children: _jsx(Database, { size: 100 }) }), _jsx("div", { className: "p-3 bg-blue-600 rounded-2xl shadow-lg shrink-0", children: _jsx(Database, { size: 20 }) }), _jsxs("div", { className: "text-left space-y-2 relative z-10", children: [_jsx("h4", { className: "text-xs font-black uppercase text-blue-400 tracking-widest italic leading-none", children: "Status Rapportage" }), _jsxs("p", { className: "text-[11px] text-slate-400 font-bold uppercase leading-relaxed tracking-wider opacity-80 max-w-3xl", children: ["Deze tabel synchroniseert real-time met", " ", _jsx("strong", { children: "/future-factory/settings/blueprint_configs/main" }), ". Blauwdrukken die hier verschijnen worden automatisch gebruikt door de ", _jsx("strong", { children: "Maatvoering" }), " module om invoervelden te genereren."] })] })] })] }));
};
export default SpecsView;
