import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from "react-i18next";
import { AlertTriangle, Layers } from "lucide-react";
const OverproductionPanel = ({ overproductionGroups, onOpenOverproductionGroup, resolveOverproductionRoute, }) => {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "mb-4 shrink-0 rounded-[32px] border border-amber-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsxs("p", { className: "text-[10px] font-black uppercase tracking-[0.25em] text-amber-600 flex items-center gap-2", children: [_jsx(AlertTriangle, { size: 14 }), " ", t("teamleader.overproduction", "Overproduction")] }), _jsx("h3", { className: "text-lg font-black text-slate-900 italic mt-2", children: t("teamleader.pending_extra_products", "Open pending extra products") }), _jsx("p", { className: "text-xs font-bold text-slate-500 mt-1", children: t("teamleader.link_extras_help", "Koppel extras aan een nieuw LN-ordernummer en stuur ze direct door naar de juiste vervolgstap.") })] }), _jsx("div", { className: "px-3 py-2 rounded-2xl bg-white border border-amber-200 text-amber-700 text-sm font-black min-w-[3rem] text-center", children: overproductionGroups.length })] }), _jsx("div", { className: "mt-4 space-y-3 max-h-[18rem] overflow-y-auto custom-scrollbar pr-1", children: overproductionGroups.length === 0 ? (_jsx("div", { className: "rounded-2xl border border-dashed border-amber-200 bg-white/70 px-4 py-5 text-xs font-bold text-slate-400 uppercase tracking-widest text-center", children: t("teamleader.no_pending_overproduction", "Geen openstaande overproductie") })) : (overproductionGroups.map((group) => {
                    const sampleRoute = resolveOverproductionRoute({ machine: group.originMachine, item: group.item }, group, "");
                    return (_jsx("button", { onClick: () => onOpenOverproductionGroup(group), className: "w-full rounded-2xl border border-amber-100 bg-white px-4 py-3 text-left hover:border-amber-300 hover:bg-amber-50/40 transition-all", children: _jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("span", { className: "text-sm font-black text-slate-900", children: group.originalOrderId }), _jsx("span", { className: "px-2 py-0.5 rounded-lg bg-amber-100 text-amber-700 text-[10px] font-black uppercase tracking-widest", children: t("teamleader.extra_count", "{{count}} extra", { count: group.count }) })] }), _jsx("p", { className: "text-xs font-bold text-slate-600 mt-1 truncate", children: group.item || "Onbekend product" }), _jsxs("p", { className: "text-[10px] font-bold uppercase tracking-widest text-slate-400 mt-2", children: ["Bron: ", group.originMachine || "-", " \u00B7 Route: ", sampleRoute.station || "Handmatig"] })] }), _jsxs("div", { className: "flex items-center gap-2 text-amber-600 font-black text-xs uppercase", children: [_jsx(Layers, { size: 14 }), " ", group.lotNumbers.length] })] }) }, group.key));
                })) })] }));
};
export default OverproductionPanel;
