import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLocation } from "react-router-dom";
import { X, ArrowRightLeft, Trash2, Loader2 } from "lucide-react";
/**
 * Modal om individuele units handmatig te verplaatsen in het proces.
 */
const LotOverrideModal = ({ isOpen, onClose, lotData, setLotData, onSave, onDelete, loading, stations, steps, }) => {
    const location = useLocation();
    if (!isOpen || !lotData || location.pathname.includes("/login"))
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-slate-900/80 backdrop-blur-xl z-[150] flex items-center justify-center p-8 animate-in fade-in", children: _jsxs("div", { className: "bg-white w-full max-w-xl rounded-[50px] shadow-2xl border border-slate-100 overflow-hidden flex flex-col animate-in zoom-in-95 text-left", children: [_jsxs("div", { className: "p-8 bg-slate-900 text-white flex justify-between items-center shrink-0", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "p-3 bg-rose-500 rounded-2xl shadow-lg", children: _jsx(ArrowRightLeft, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-black italic uppercase leading-none", children: "Product Override" }), _jsxs("p", { className: "text-[10px] font-bold text-slate-400 uppercase mt-1", children: ["Lot: ", lotData.lotNumber] })] })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-white/10 rounded-xl transition-all", children: _jsx(X, { size: 24 }) })] }), _jsxs("div", { className: "p-10 space-y-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-[10px] font-black text-slate-400 uppercase mb-2", children: "HANDMATIGE LOCATIE" }), _jsx("select", { className: "w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm font-bold outline-none focus:border-blue-500", value: lotData.currentStation, onChange: (e) => setLotData({ ...lotData, currentStation: e.target.value }), children: stations.map((stationItem) => (_jsx("option", { value: stationItem.id, children: stationItem.name }, stationItem.id))) })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-[10px] font-black text-slate-400 uppercase mb-2", children: "PROCES STAP" }), _jsx("select", { className: "w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm font-bold outline-none focus:border-blue-500", value: lotData.currentStep, onChange: (e) => setLotData({ ...lotData, currentStep: e.target.value }), children: steps.map((stepItem) => (_jsx("option", { value: stepItem, children: stepItem }, stepItem))) })] })] }), _jsxs("div", { className: "pt-6 border-t border-slate-100 flex flex-col gap-3", children: [_jsxs("button", { onClick: onSave, disabled: loading, className: "w-full bg-slate-900 text-white py-5 rounded-3xl font-black text-xs uppercase tracking-widest hover:bg-blue-600 transition-all shadow-xl flex items-center justify-center gap-2", children: [loading && _jsx(Loader2, { size: 16, className: "animate-spin" }), " ", "Verplaatsing Bevestigen"] }), _jsxs("button", { onClick: () => onDelete(lotData.lotNumber), className: "w-full py-4 text-xs font-black text-red-500 hover:bg-red-50 rounded-2xl transition-all uppercase flex items-center justify-center gap-2 italic", children: [_jsx(Trash2, { size: 16 }), " Lot Verwijderen"] })] })] })] }) }));
};
export default LotOverrideModal;
