import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useLocation } from "react-router-dom";
import { X, Settings2, Loader2, Save, Trash2 } from "lucide-react";
/**
 * Modal voor het aanpassen of verwijderen van orders door Admins/Teamleaders.
 */
const OrderEditModal = ({ isOpen, onClose, formData, setFormData, onSave, onDelete, loading, stations, }) => {
    const location = useLocation();
    if (!isOpen || location.pathname.includes("/login"))
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-slate-900/80 backdrop-blur-xl z-[150] flex items-center justify-center p-8 animate-in fade-in", children: _jsxs("div", { className: "bg-white w-full max-w-2xl rounded-[50px] shadow-2xl border border-slate-100 flex flex-col animate-in zoom-in-95 duration-500 overflow-hidden text-left", children: [_jsxs("div", { className: "p-8 bg-slate-900 text-white flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "p-3 bg-blue-500 rounded-2xl shadow-lg", children: _jsx(Settings2, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-black italic uppercase leading-none", children: "Order Management" }), _jsx("p", { className: "text-[10px] font-bold text-slate-400 uppercase mt-1", children: "Aanpassing & Beheer" })] })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-white/10 rounded-xl transition-all", children: _jsx(X, { size: 24 }) })] }), _jsxs("div", { className: "p-10 space-y-6", children: [_jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-[10px] font-black text-slate-400 uppercase mb-2", children: "Machine" }), _jsx("select", { className: "w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm font-bold outline-none focus:border-blue-500 transition-all", value: formData.machine, onChange: (e) => setFormData({ ...formData, machine: e.target.value }), children: stations
                                                .filter((s) => s.type === "machine")
                                                .map((stationItem) => (_jsx("option", { value: stationItem.id, children: stationItem.id }, stationItem.id))) })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-[10px] font-black text-slate-400 uppercase mb-2", children: "Plan Aantal" }), _jsx("input", { type: "number", className: "w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm font-bold outline-none focus:border-blue-500 transition-all", value: formData.plan, onChange: (e) => setFormData({ ...formData, plan: e.target.value }) })] }), _jsxs("div", { className: "col-span-2", children: [_jsx("label", { className: "block text-[10px] font-black text-slate-400 uppercase mb-2", children: "Actief Lotnummer" }), _jsx("input", { type: "text", className: "w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm font-bold outline-none focus:border-blue-500 transition-all", value: formData.activeLot || "", onChange: (e) => setFormData({ ...formData, activeLot: e.target.value }), placeholder: "Bijv. 26-01-0001" })] })] }), _jsxs("div", { className: "pt-8 border-t border-slate-100 flex flex-col gap-3", children: [_jsxs("button", { onClick: onSave, disabled: loading, className: "w-full bg-blue-600 text-white py-5 rounded-3xl font-black text-xs uppercase tracking-widest hover:bg-blue-700 shadow-xl flex items-center justify-center gap-3 active:scale-95 transition-all", children: [loading ? (_jsx(Loader2, { size: 18, className: "animate-spin" })) : (_jsx(Save, { size: 18 })), " ", "Wijzigingen Opslaan"] }), _jsxs("button", { onClick: () => onDelete(formData.id), className: "w-full py-4 text-xs font-black text-red-500 hover:bg-red-50 rounded-2xl transition-all uppercase flex items-center justify-center gap-2 underline tracking-widest", children: [_jsx(Trash2, { size: 16 }), " Order Verwijderen"] })] })] })] }) }));
};
export default OrderEditModal;
