import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { X, Layers, Monitor, Clock, Tv } from "lucide-react";
import { FITTING_MACHINES, PIPE_MACHINES } from "../../../utils/hubHelpers.tsx";
const TerminalSelectionModal = ({ onClose }) => {
    const navigate = useNavigate();
    const handleSelect = (machine) => {
        navigate(`/terminal/${machine}`);
        onClose();
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black/60 z-[70] flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in", children: _jsxs("div", { className: "bg-white rounded-3xl shadow-2xl w-full max-w-3xl border border-gray-100 flex flex-col overflow-hidden max-h-[80vh]", children: [_jsxs("div", { className: "p-6 border-b flex justify-between items-center bg-slate-50", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-black text-slate-800 uppercase italic", children: "Selecteer Workstation" }), _jsx("p", { className: "text-xs text-gray-500", children: "Kies een machine om de terminal te openen" })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-slate-200 rounded-full transition-colors", children: _jsx(X, { size: 24, className: "text-slate-500" }) })] }), _jsx("div", { className: "p-8 overflow-y-auto custom-scrollbar", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8", children: [_jsxs("div", { children: [_jsxs("h4", { className: "text-xs font-black text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2", children: [_jsx(Layers, { size: 14 }), " Fittings & Specials"] }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: FITTING_MACHINES.map((m) => (_jsxs("button", { onClick: () => handleSelect(m), className: "p-4 bg-white border-2 border-slate-100 hover:border-blue-500 hover:bg-blue-50 rounded-xl font-black text-slate-700 hover:text-blue-700 transition-all text-sm flex flex-col items-center gap-2 group", children: [_jsx(Monitor, { size: 24, className: "text-slate-300 group-hover:text-blue-500" }), m] }, m))) })] }), _jsxs("div", { children: [_jsxs("h4", { className: "text-xs font-black text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2", children: [_jsx(Clock, { size: 14 }), " Pipes & Spools"] }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: PIPE_MACHINES.map((m) => (_jsxs("button", { onClick: () => handleSelect(m), className: "p-4 bg-white border-2 border-slate-100 hover:border-cyan-500 hover:bg-cyan-50 rounded-xl font-black text-slate-700 hover:text-cyan-700 transition-all text-sm flex flex-col items-center gap-2 group", children: [_jsx(Tv, { size: 24, className: "text-slate-300 group-hover:text-cyan-500" }), m] }, m))) })] })] }) })] }) }));
};
export default TerminalSelectionModal;
