import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App"; // Schakelt weer over naar de hoofdapplicatie
import ErrorBoundary from "./components/ErrorBoundary";
import { auth, logActivity } from "./config/firebase";
import "./i18n"; // Import i18n configuratie
import "./styles.css";

declare global {
  interface Window {
    eruda?: {
      init: () => void;
    };
  }
}

const recentRuntimeErrors = new Map();

const reportRuntimeError = (type: string, details: unknown): void => {
  try {
    const fingerprint = `${type}:${details}`.slice(0, 200);
    const now = Date.now();
    const prev = recentRuntimeErrors.get(fingerprint) || 0;

    // Throttle duplicate errors to avoid spamming logs.
    if (now - prev < 30000) return;
    recentRuntimeErrors.set(fingerprint, now);

    logActivity(
      auth.currentUser?.uid || "system",
      "CLIENT_RUNTIME_ERROR",
      `${type}: ${String(details || "unknown").slice(0, 1200)}`
    ).catch(() => {});
  } catch {
    // Best effort error reporting only.
  }
};

const shouldAttachManifest = (() => {
  if (typeof window === "undefined") return false;
  const host = String(window.location.hostname || "").toLowerCase();
  // GitHub dev preview can redirect manifest requests through auth endpoints,
  // which causes noisy CORS errors in console without impacting app runtime.
  return !host.endsWith(".app.github.dev");
})();

if (shouldAttachManifest) {
  const existingManifest = document.querySelector('link[rel="manifest"]');
  if (!existingManifest) {
    const manifestLink = document.createElement("link");
    manifestLink.rel = "manifest";
    manifestLink.href = "/manifest.json";
    document.head.appendChild(manifestLink);
  }
}

/**
 * FPi Future Factory - Main Entry Point
 * Versie: 4.1 (Safari/iPad Fix)
 * * Dit bestand initialiseert de React applicatie en koppelt deze aan
 * de HTML-structuur in index.html.
 * * ErrorBoundary toegevoegd voor betere foutafhandeling op Safari/iPad
 */

// Debug logging voor Safari/iPad issues

// Eruda debug console voor iPad/mobiel (activeer met ?debug=true in URL)
if (window.location.search.includes('debug=true') || localStorage.getItem('eruda-debug') === 'true') {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/eruda';
  script.onload = () => {
    if (window.eruda) {
      window.eruda.init();
    }
  };
  document.body.appendChild(script);
}

const rootElement = document.getElementById("root");

if (!rootElement) {
  // Foutafhandeling voor als het root element ontbreekt
  console.error(
    "CRITICAL ERROR: Het element met id 'root' is niet gevonden in de HTML."
  );
} else {
  const root = ReactDOM.createRoot(rootElement);

  root.render(
    <React.StrictMode>
      <ErrorBoundary>
        {/* BrowserRouter zorgt voor de navigatie binnen de MES-omgeving */}
        <BrowserRouter future={{
          v7_startTransition: true,
          v7_relativeSplatPath: true
        }}>
          <App />
        </BrowserRouter>
      </ErrorBoundary>
    </React.StrictMode>
  );
}

// Global error handler voor uncaught errors op Safari
window.addEventListener('error', (event) => {
  console.error('🔴 Global error caught:', event.error);
  console.error('🔴 Error message:', event.message);
  console.error('🔴 Error filename:', event.filename);
  console.error('🔴 Error line:', event.lineno);
  reportRuntimeError(
    'window.error',
    `${event.message || 'unknown'} @ ${event.filename || 'unknown'}:${event.lineno || 0}`
  );
});

// Promise rejection handler voor Safari
window.addEventListener('unhandledrejection', (event) => {
  const reason = event?.reason;
  const message = String(reason?.message || reason || "");

  // Ignore common browser-extension noise that is not generated by this app.
  if (/frame with id .* was removed|no tab with id/i.test(message)) {
    return;
  }

  console.error('🔴 Unhandled promise rejection:', reason);
  reportRuntimeError('window.unhandledrejection', message || reason?.stack || 'unknown');
});
